name: Build and Artifact the ESP-IDF Project

on:
  push:

  workflow_dispatch:
env:
  IDF_PATH: /home/runner/work/esp32-to-micropython/esp32-to-micropython/esp-idf
  ADF_PATH: /home/runner/work/esp32-to-micropython/esp32-to-micropython/esp-adf
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get install git wget flex bison gperf python3.11 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util
          cmake --version
          python3 --version

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install ESP-IDF
        run:  |
            pwd
            ls -lh
            ./esp-idf/install.sh
            . $IDF_PATH/export.sh
            cd micropython/ports/esp32
            make BOARD=ESP32_GENERIC_S3 submodules
            make BOARD=ESP32_GENERIC_S3 all

      - name: Set up the environment variables
        run:  |
            cd $IDF_PATH
            git apply ${ADF_PATH}/idf_patches/idf_v5.0_freertos.patch
            rm ${IDF_PATH}/components/fatfs/CMakeLists.txt
            . $IDF_PATH/export.sh
            cd ../micropython/ports/esp32
            git apply ${ADF_PATH}/micropython_adf/mp.diff
            make USER_C_MODULES=${ADF_PATH}/micropython_adf/mod/micropython.cmake BOARD_DIR=${ADF_PATH}/micropython_adf/boards/korvo2v3 all
            
      - name: Archive build output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-audio
          path: |
            micropython/ports/esp32/build-korvo2v3/firmware.bin

