name: Build audio bin

on:
  push:

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get install python3.11 

      - name: Checkout repo
        uses: actions/checkout@v3
          
      - name: build audio bin
        run:  python3 audio/mk_audio_tone.py -f ./ -r audio

      - name: Archive build output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: audio_tone.bin
          path: audio/audio_tone.bin


